name: spotiflow
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - cpuonly
  - git # Needed to install from GitHub
  - pip:
      - git+https://github.com/weigertlab/spotiflow@0.3.0
