name: kb_count
## TODO nf-core: Add a description of the module and list keywords
description: quantifies scRNA-seq data from fastq files using kb-python
keywords:
  - sort
tools:
  - kb:
      description: kallisto and bustools are wrapped in an easy-to-use program called kb
      homepage: https://www.kallistobus.tools/
      documentation: https://kb-python.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/pachterlab/kb_python
      doi: ""
      licence: BSD 3-Clause License

## TODO nf-core: Add a description of all of the variables used as input
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  ## TODO nf-core: Delete / customise this example input
  - fastq1:
      type: file
      description: Read 1 fastq file
      pattern: "*.{fastq.gz,fastq}"
  - fastq2:
      type: file
      description: Read 2 fastq file
      pattern: "*.{fastq.gz,fastq}"
  - index:
      type: file
      description: kb-ref index file (.idx)
      pattern: "*.{idx}"
  - t2g:
      type: file
      description: t2g file from kallisto
      pattern: "*t2g.txt"
  - t1c:
      type: file
      description: kb ref's c1 spliced_t2c file
      pattern: "*.{.txt}"
  - use_t1c:
      type: boolean
      description: Whether to use the c1 txt file for RNA velocity
  - t2c:
      type: file
      description: kb ref's c2 unspliced_t2c file
  - use_t2c:
      type: boolean
      description: Whether to use the c2 txt file for RNA velocity

## TODO nf-core: Add a description of all of the variables used as output
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - output:
      type: file
      description: output folder
      pattern: "output"

authors:
  - "@flowuenne"
