name: kallistobustools_ref
description: index creation for kb count quantification of single-cell data.
keywords:
  - kallisto-bustools
  - index
tools:
  - kb:
      description: kallisto|bustools (kb) is a tool developed for fast and efficient processing of single-cell OMICS data.
      homepage: https://www.kallistobus.tools/
      documentation: https://kb-python.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/pachterlab/kb_python
      doi: "https://doi.org/10.22002/D1.1876"
      licence: MIT License

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', --workflow ]
  - fasta:
      type: file
      description: Genomic DNA fasta file
      pattern: "*.{fasta,fasta.gz}"

  - gtf:
      type: file
      description: GTF gene annotation file for fasta
      pattern: "*.{gtf,gtf.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - kb_ref_idx:
      type: file
      description: Index file from kb ref.
      pattern: "*.{idx}"
  - t2g:
      type: file
      description: Transcript to gene table
      pattern: "*.{txt}"
  - cdna:
      type: file
      description: Cdna fasta file
      pattern: "*cdna.{fa}"
  - intron:
      type: file
      description: intron fasta file
      pattern: "*intron.{fa}"
  - cdna_t2c:
      type: file
      description: cdna transcript to capture file
      pattern: "*cdna_t2c.{txt}"
  - intron_t2c:
      type: file
      description: intron transcript to capture file
      pattern: "*intron_t2c.{txt}"

authors:
  - "@flowuenne"
